# Generated by Django 5.2.9 on 2025-12-17 14:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0002_course_image_delete_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='erp.subject'),
        ),
    ]
