# Generated by Django 5.2.9 on 2025-12-17 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0003_module_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='homework',
            field=models.CharField(default='No homework', max_length=500),
        ),
    ]
